### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [diharaw/dwSampleFramework#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114010288-880cf900-9896-11eb-8c11-73df47e01c71.png)

thank you  
best regards to you  
William

**Comment by diharaw** [comment]
Hi,

Did you clone the FFTOceanWaves repository recursively? Because it seems like the issue might be caused by using the wrong version of the dwSampleFramework. 

Use the git clone —recursive command.

Dihara

**Comment by WilliamWangPeng** [comment]
> Hi,
> 
> Did you clone the FFTOceanWaves repository recursively? Because it seems like the issue might be caused by using the wrong version of the dwSampleFramework.
> 
> Use the git clone —recursive command.
> 
> Dihara

hi dear @diharaw   
    do you have a mirror including all of the external folder?  
    I have tried    
         git clone —recursive command.  

     for many times but failed in the end.  

thank you

**Comment by diharaw** [comment]
Did you use the full command?

`git clone --recursive https://github.com/diharaw/FFTOceanWaves.git`
